set_property SRC_FILE_INFO {cfile:/home/audrey/Documents/convolution/Map_inflation/hardware_impl/timingConstraint.xdc rfile:../../timingConstraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y11 [get_cells {{weight_loader_inst/weight_storage_reg[15]} {weight_loader_inst/weight_storage_reg[7]}}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_LOC_FIXED TRUE [get_cells {{weight_loader_inst/weight_storage_reg[15]} {weight_loader_inst/weight_storage_reg[7]}}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X34Y8 [get_cells {{weight_loader_inst/weight_storage_reg[2]} {weight_loader_inst/weight_storage_reg[23]} {weight_loader_inst/weight_storage_reg[22]} {weight_loader_inst/weight_storage_reg[10]}}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_LOC_FIXED TRUE [get_cells {{weight_loader_inst/weight_storage_reg[2]} {weight_loader_inst/weight_storage_reg[23]} {weight_loader_inst/weight_storage_reg[22]} {weight_loader_inst/weight_storage_reg[10]}}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X34Y7 [get_cells {{accumulator_inst/in_buf_data_reg[21]} {accumulator_inst/in_buf_data_reg[20]} {accumulator_inst/in_buf_data_reg[17]} {accumulator_inst/in_buf_data_reg[16]}}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_LOC_FIXED TRUE [get_cells {{accumulator_inst/in_buf_data_reg[21]} {accumulator_inst/in_buf_data_reg[20]} {accumulator_inst/in_buf_data_reg[17]} {accumulator_inst/in_buf_data_reg[16]}}]
